-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 18:08:40 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_reserva
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_reserva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_reserva` DEFAULT CHARACTER SET utf8 COLLATE utf8_icelandic_ci ;
USE `bd_reserva` ;

-- -----------------------------------------------------
-- Table `bd_reserva`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`habitacion` (
  `idhabitacion` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(5) NOT NULL,
  `piso` VARCHAR(2) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `precio_diario` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `tipo_habitacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idhabitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_reserva`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apaterno` VARCHAR(25) NOT NULL,
  `amaterno` VARCHAR(25) NOT NULL,
  `tipo_documento` VARCHAR(15) NOT NULL,
  `num_documento` VARCHAR(8) NOT NULL,
  `direccion` VARCHAR(80) NULL,
  `telefono` VARCHAR(10) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_reserva`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`trabajador` (
  `id_persona` INT NOT NULL,
  `sueldo` DECIMAL(7,2) NOT NULL,
  `acceso` VARCHAR(15) NOT NULL,
  `usuario` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`id_persona`)
    REFERENCES `bd_reserva`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_reserva`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NULL,
  `descripcion` VARCHAR(255) NULL,
  `unidad_medida` VARCHAR(20) NULL,
  `precio_venta` DECIMAL(7,2) NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_reserva`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`cliente` (
  `id_persona` INT NOT NULL,
  `codigo_cliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `codigo_cliente_UNIQUE` (`codigo_cliente` ASC),
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`id_persona`)
    REFERENCES `bd_reserva`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_reserva`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_habitacion` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_trabajador` INT NOT NULL,
  `tipo_reserva` VARCHAR(20) NOT NULL,
  `fecha_reserva` DATE NOT NULL,
  `fecha_ingresa` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `costo_alojamiento` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_habitacion_idx` (`id_habitacion` ASC),
  INDEX `fk_reserva_cliente_idx` (`id_cliente` ASC),
  INDEX `fk_reserva_trabajador_idx` (`id_trabajador` ASC),
  CONSTRAINT `fk_reserva_habitacion`
    FOREIGN KEY (`id_habitacion`)
    REFERENCES `bd_reserva`.`habitacion` (`idhabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `bd_reserva`.`cliente` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_trabajador`
    FOREIGN KEY (`id_trabajador`)
    REFERENCES `bd_reserva`.`trabajador` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_reserva`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`consumo` (
  `id_consumo` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` DECIMAL(7,2) NOT NULL,
  `precio_venta` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_consumo`),
  INDEX `fk_consumo_reserva_idx` (`id_reserva` ASC),
  INDEX `fk_consumo_producto_idx` (`id_producto` ASC),
  CONSTRAINT `fk_consumo_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `bd_reserva`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `bd_reserva`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_reserva`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_reserva`.`pago` (
  `id_pago` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NOT NULL,
  `tipo_comprobante` VARCHAR(15) NOT NULL,
  `num_comprobante` VARCHAR(15) NOT NULL,
  `igv` DECIMAL(7,2) NOT NULL,
  `total_pago` DECIMAL(7,2) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  `fecha_pago` DATE NOT NULL,
  PRIMARY KEY (`id_pago`),
  INDEX `fk_pago_reserva_idx` (`id_reserva` ASC),
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `bd_reserva`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
